---

- hosts: all
  tasks:
    - name: apt source
      become: yes
      become_method: sudo
      ansible.builtin.copy:
        src: apt/sources.list
        dest: /etc/apt/sources.list
    - name: kubesphere packages
      become: yes
      become_method: sudo
      apt:
        update_cache: yes
        pkg:
          - nfs-common
          - socat
          - conntrack
          - ebtables
          - ipset
          - docker.io
          - avahi-daemon
          - tmux
          - dstat
        state: present
    - name: shared mount point
      become: yes
      become_method: sudo
      ansible.builtin.file:
        path: /mnt/shared
        state: directory
        mode: '0755'
    - name: mount shared nfs
      become: yes
      become_method: sudo
      ansible.posix.mount:
        src: 192.168.1.7:/mnt/trunk
        path: /mnt/shared
        opts: rw,sync
        state: mounted
        fstype: nfs
    - name: open files ulimit
      become: yes
      become_method: sudo
      community.general.pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nofile
        value: 1048576
    - name: processes ulimit
      become: yes
      become_method: sudo
      community.general.pam_limits:
        domain: '*'
        limit_type: '-'
        limit_item: nproc
        value: 1048576
    - name: docker daemon.json
      become: yes
      become_method: sudo
      ansible.builtin.copy:
        src: docker/daemon.json
        dest: /etc/docker/daemon.json
      register: docker_config
    - name: docker proxy config
      become: yes
      become_method: sudo
      ansible.builtin.copy:
        src: docker.service.d/
        dest: /etc/systemd/system/docker.service.d/
      register: docker_config
    - name: docker reload
      become: yes
      become_method: sudo
      ansible.builtin.systemd:
        daemon_reload: yes
        state: restarted
        name: docker
      when: docker_config.changed
    - name: tmux config
      ansible.builtin.copy:
        src: home/tmux.conf
        dest: /home/g4z3/.tmux.conf
    - name: g4z3 groups
      become: yes
      become_method: sudo
      ansible.builtin.user:
        name: g4z3
        groups: sudo, docker
        append: yes
    - name: firmware
      become: yes
      become_method: sudo
      ansible.builtin.copy:
        src: firmware/cmdline.txt
        dest: /boot/firmware/cmdline.txt
      register: firmware_config
    - name: reboot
      become: yes
      become_method: sudo
      reboot:
        reboot_timeout: 600
      when: firmware_config.changed
